import type { GrowthScoreBand, GrowthScoreCategoryConfig } from "@/types";

/**
 * NEXT LEVEL GROWTH SCORE — CENTRALIZED CONFIGURATION
 * ------------------------------------------------------------------
 * The single source of truth for every category, question, weight, and
 * threshold behind the score. engine.ts contains zero hard-coded scoring
 * content — everything it operates on comes from here, so the score stays
 * "traceable to defined scoring criteria" rather than logic scattered
 * across components. Category weights sum to 100 for readability, but the
 * engine renormalizes across whatever categories were actually evaluated,
 * so that isn't a hard requirement of the format.
 *
 * Every question offers exactly the options listed here PLUS two universal
 * answers the engine always appends: "I don't know" and "Not applicable" —
 * those are never part of a category's option list.
 *
 * relevantIndustries is "all" for every category in this phase — the
 * filtering mechanism (growth-score/engine.ts's category selection) is
 * fully implemented and industry-aware, but populating real per-industry
 * exclusion rules is a Phase-4 content pass, documented as a known
 * limitation rather than faked with arbitrary rules.
 */

export const SCORE_BANDS: GrowthScoreBand[] = [
  { min: 0, max: 39, label: "Foundation at Risk", message: "There's real opportunity here. The foundation needs deliberate attention before growth efforts will compound." },
  { min: 40, max: 54, label: "Early Growth Stage", message: "The basics are taking shape. A few focused priorities will move this forward quickly." },
  { min: 55, max: 69, label: "Building Momentum", message: "Real progress is visible. The next priorities are about removing friction, not starting over." },
  { min: 70, max: 84, label: "Strong Growth Foundation", message: "This is a well-built business. The opportunity now is refinement and scale, not repair." },
  { min: 85, max: 100, label: "Ready to Scale Carefully", message: "A genuinely strong foundation. The priority is scaling deliberately without letting quality or sustainability slip." },
];

export const CONFIDENCE_THRESHOLDS = {
  insufficient: 0,
  low: 0.25,
  moderate: 0.5,
  high: 0.8,
} as const;

export const GROWTH_SCORE_CATEGORIES: GrowthScoreCategoryConfig[] = [
  {
    id: "business-foundation",
    label: "Business Foundation",
    description: "How clear and established the core business is.",
    weight: 8,
    enabled: true,
    relevantIndustries: "all",
    displayOrder: 1,
    effortProxy: 3,
    thresholds: { strong: 70, weak: 40 },
    positiveIndicatorHints: ["A clearly defined offer and audience", "An established, operating business"],
    riskIndicatorHints: ["An unclear or still-forming offer", "A very early-stage or untested business"],
    recommendedActionsByWeakness: [
      "Write a one-sentence description of who you help and what specific outcome you deliver.",
      "Test that description on five real prospects and refine it based on what confuses them.",
    ],
    relatedServiceIds: ["branding-positioning"],
    questions: [
      {
        id: "foundation-offer-clarity",
        categoryId: "business-foundation",
        prompt: "How clear is your core offer and who it's for?",
        signal: "positive",
        weight: 1,
        quickCheck: true,
        maxPoints: 4,
        options: [
          { value: "crystal-clear", label: "Crystal clear", points: 4 },
          { value: "mostly-clear", label: "Mostly clear", points: 3 },
          { value: "somewhat-unclear", label: "Somewhat unclear", points: 1 },
          { value: "not-defined", label: "Not really defined yet", points: 0 },
        ],
      },
      {
        id: "foundation-time-in-business",
        categoryId: "business-foundation",
        prompt: "How long has the business been operating?",
        signal: "risk",
        weight: 1,
        quickCheck: false,
        maxPoints: 4,
        options: [
          { value: "3-plus-years", label: "3+ years", points: 4 },
          { value: "1-3-years", label: "1–3 years", points: 3 },
          { value: "under-1-year", label: "Under a year", points: 2 },
          { value: "just-starting", label: "Just starting out", points: 1 },
        ],
      },
    ],
  },
  {
    id: "website-digital-presence",
    label: "Website & Digital Presence",
    description: "Whether the website actually helps convert attention into contact.",
    weight: 12,
    enabled: true,
    relevantIndustries: "all",
    displayOrder: 2,
    effortProxy: 4,
    thresholds: { strong: 70, weak: 40 },
    positiveIndicatorHints: ["A modern, working website", "A clear next step on every page"],
    riskIndicatorHints: ["No website, or one that's rarely used", "No clear call-to-action for visitors"],
    recommendedActionsByWeakness: [
      "Get one clear, unmissable call-to-action above the fold on mobile.",
      "Confirm every contact method actually works on a phone.",
      "Rewrite the homepage headline around the outcome customers want.",
    ],
    relatedServiceIds: ["website-design", "website-redesign", "conversion-optimization"],
    questions: [
      {
        id: "website-working",
        categoryId: "website-digital-presence",
        prompt: "Do you have a working website today?",
        signal: "positive",
        weight: 1,
        quickCheck: true,
        maxPoints: 4,
        options: [
          { value: "modern-fast", label: "Yes, modern and fast", points: 4 },
          { value: "outdated", label: "Yes, but outdated", points: 2 },
          { value: "barely-used", label: "Yes, but barely used", points: 1 },
          { value: "no-website", label: "No website", points: 0 },
        ],
      },
      {
        id: "website-clear-cta",
        categoryId: "website-digital-presence",
        prompt: "Does your website make it obvious what to do next (call, form, book)?",
        signal: "risk",
        weight: 1,
        quickCheck: false,
        maxPoints: 4,
        options: [
          { value: "one-clear-action", label: "Yes, one clear action", points: 4 },
          { value: "sort-of", label: "Sort of", points: 2 },
          { value: "not-really", label: "Not really", points: 1 },
        ],
      },
    ],
  },
  {
    id: "local-visibility-seo",
    label: "Local Visibility & SEO",
    description: "How easily customers actively searching can find the business.",
    weight: 10,
    enabled: true,
    relevantIndustries: "all",
    displayOrder: 3,
    effortProxy: 2,
    thresholds: { strong: 70, weak: 40 },
    positiveIndicatorHints: ["A complete, active Google Business Profile", "A healthy volume of recent reviews"],
    riskIndicatorHints: ["An unclaimed or incomplete Google Business Profile", "Few or no reviews"],
    recommendedActionsByWeakness: [
      "Fully complete the Google Business Profile: hours, categories, service area, photos.",
      "Ask the next five satisfied customers directly for a review, in the moment.",
    ],
    relatedServiceIds: ["local-seo", "gbp-optimization"],
    questions: [
      {
        id: "visibility-gbp-complete",
        categoryId: "local-visibility-seo",
        prompt: "Is your Google Business Profile claimed and complete?",
        signal: "positive",
        weight: 1,
        quickCheck: true,
        maxPoints: 4,
        options: [
          { value: "complete", label: "Yes, fully complete", points: 4 },
          { value: "incomplete", label: "Claimed but incomplete", points: 2 },
          { value: "not-claimed", label: "Not claimed", points: 0 },
        ],
      },
      {
        id: "visibility-review-count",
        categoryId: "local-visibility-seo",
        prompt: "Roughly how many reviews do you have?",
        signal: "risk",
        weight: 1,
        quickCheck: false,
        maxPoints: 4,
        options: [
          { value: "20-plus", label: "20+", points: 4 },
          { value: "5-20", label: "5–20", points: 3 },
          { value: "1-5", label: "1–5", points: 1 },
          { value: "none", label: "None yet", points: 0 },
        ],
      },
    ],
  },
  {
    id: "lead-generation",
    label: "Lead Generation",
    description: "How consistently new potential customers enter the pipeline.",
    weight: 12,
    enabled: true,
    relevantIndustries: "all",
    displayOrder: 4,
    effortProxy: 4,
    thresholds: { strong: 70, weak: 40 },
    positiveIndicatorHints: ["A steady, trackable flow of new leads"],
    riskIndicatorHints: ["Inconsistent or untracked lead flow"],
    recommendedActionsByWeakness: [
      "Identify your single best-performing lead source and double down before adding new ones.",
      "Add a simple 'how did you hear about us' habit so channels become trackable.",
    ],
    relatedServiceIds: ["lead-generation", "marketing-strategy", "lead-capture-systems"],
    questions: [
      {
        id: "leads-consistency",
        categoryId: "lead-generation",
        prompt: "How consistent is your flow of new leads?",
        signal: "positive",
        weight: 1,
        quickCheck: true,
        maxPoints: 4,
        options: [
          { value: "steady", label: "Steady and predictable", points: 4 },
          { value: "uneven", label: "Some months good, some bad", points: 2 },
          { value: "rare", label: "Rare or inconsistent", points: 1 },
          { value: "almost-none", label: "Almost none", points: 0 },
        ],
      },
      {
        id: "leads-channel-known",
        categoryId: "lead-generation",
        prompt: "Do you know which channel brings the most leads?",
        signal: "risk",
        weight: 1,
        quickCheck: false,
        maxPoints: 4,
        options: [
          { value: "tracked", label: "Yes, it's tracked", points: 4 },
          { value: "rough-idea", label: "Rough idea", points: 2 },
          { value: "no-idea", label: "No idea", points: 0 },
        ],
      },
    ],
  },
  {
    id: "sales-follow-up",
    label: "Sales & Follow-Up",
    description: "What happens after a customer reaches out.",
    weight: 10,
    enabled: true,
    relevantIndustries: "all",
    displayOrder: 5,
    effortProxy: 2,
    thresholds: { strong: 70, weak: 40 },
    positiveIndicatorHints: ["Fast, consistent response to new inquiries", "A real follow-up process"],
    riskIndicatorHints: ["Slow or inconsistent response time", "No follow-up process for quiet leads"],
    recommendedActionsByWeakness: [
      "Set a one-hour response standard for every new inquiry.",
      "Build a short, consistent follow-up sequence for leads who go quiet.",
    ],
    relatedServiceIds: ["crm-setup", "follow-up-automation"],
    questions: [
      {
        id: "sales-response-speed",
        categoryId: "sales-follow-up",
        prompt: "How fast do you typically respond to a new inquiry?",
        signal: "positive",
        weight: 1,
        quickCheck: true,
        maxPoints: 4,
        options: [
          { value: "within-hour", label: "Within the hour", points: 4 },
          { value: "same-day", label: "Same day", points: 3 },
          { value: "a-day-or-two", label: "A day or two", points: 1 },
          { value: "whenever", label: "Whenever I get to it", points: 0 },
        ],
      },
      {
        id: "sales-followup-process",
        categoryId: "sales-follow-up",
        prompt: "Do you have a follow-up process for leads who don't respond right away?",
        signal: "risk",
        weight: 1,
        quickCheck: false,
        maxPoints: 4,
        options: [
          { value: "consistent", label: "Yes, consistent", points: 4 },
          { value: "sometimes", label: "Sometimes", points: 2 },
          { value: "no-process", label: "No", points: 0 },
        ],
      },
    ],
  },
  {
    id: "customer-experience-retention",
    label: "Customer Experience & Retention",
    description: "Whether customers come back and whether that's known.",
    weight: 8,
    enabled: true,
    relevantIndustries: "all",
    displayOrder: 6,
    effortProxy: 3,
    thresholds: { strong: 70, weak: 40 },
    positiveIndicatorHints: ["Meaningful repeat business", "A working feedback loop"],
    riskIndicatorHints: ["Little repeat business", "No way to collect customer feedback"],
    recommendedActionsByWeakness: [
      "Add one simple, low-friction way to collect feedback after a purchase or job.",
      "Identify your single best repeat-customer trigger and make it repeatable.",
    ],
    relatedServiceIds: ["reputation-reviews", "crm-setup"],
    questions: [
      {
        id: "retention-repeat-revenue",
        categoryId: "customer-experience-retention",
        prompt: "Do repeat customers make up a meaningful share of revenue?",
        signal: "positive",
        weight: 1,
        quickCheck: true,
        maxPoints: 4,
        options: [
          { value: "significant", label: "Yes, significant", points: 4 },
          { value: "some", label: "Some", points: 2 },
          { value: "rare", label: "Rare", points: 1 },
        ],
      },
      {
        id: "retention-feedback-loop",
        categoryId: "customer-experience-retention",
        prompt: "Do you have a way to collect customer feedback?",
        signal: "risk",
        weight: 1,
        quickCheck: false,
        maxPoints: 4,
        options: [
          { value: "regularly", label: "Yes, regularly", points: 4 },
          { value: "occasionally", label: "Occasionally", points: 2 },
          { value: "no-feedback", label: "No", points: 0 },
        ],
      },
    ],
  },
  {
    id: "brand-trust",
    label: "Brand & Trust",
    description: "Whether the business looks and feels credible to a new visitor.",
    weight: 7,
    enabled: true,
    relevantIndustries: "all",
    displayOrder: 7,
    effortProxy: 3,
    thresholds: { strong: 70, weak: 40 },
    positiveIndicatorHints: ["Consistent branding across channels", "Visible proof of credibility"],
    riskIndicatorHints: ["Inconsistent visuals or messaging", "No visible trust signals"],
    recommendedActionsByWeakness: [
      "Add a trust signal (reviews, credentials, proof) near your main call-to-action.",
      "Align visuals and messaging across your website and profiles.",
    ],
    relatedServiceIds: ["branding-positioning", "reputation-reviews"],
    questions: [
      {
        id: "brand-consistency",
        categoryId: "brand-trust",
        prompt: "Does your brand look consistent across your website and profiles?",
        signal: "positive",
        weight: 1,
        quickCheck: true,
        maxPoints: 4,
        options: [
          { value: "consistent", label: "Yes, consistent", points: 4 },
          { value: "mostly", label: "Mostly", points: 2 },
          { value: "inconsistent", label: "Inconsistent", points: 1 },
        ],
      },
      {
        id: "brand-credibility-proof",
        categoryId: "brand-trust",
        prompt: "Do you have visible proof of credibility (reviews, credentials, case studies)?",
        signal: "risk",
        weight: 1,
        quickCheck: false,
        maxPoints: 4,
        options: [
          { value: "prominent", label: "Yes, prominent", points: 4 },
          { value: "a-little", label: "A little", points: 2 },
          { value: "none", label: "None", points: 0 },
        ],
      },
    ],
  },
  {
    id: "systems-operations",
    label: "Systems & Operations",
    description: "Whether the business depends on documented process or the owner's memory.",
    weight: 9,
    enabled: true,
    relevantIndustries: "all",
    displayOrder: 8,
    effortProxy: 4,
    thresholds: { strong: 70, weak: 40 },
    positiveIndicatorHints: ["Documented core processes", "A business that runs without the owner in every moment"],
    riskIndicatorHints: ["Processes that exist only in the owner's head", "Heavy owner-dependency"],
    recommendedActionsByWeakness: [
      "Pick the single most failure-prone handoff and write down the three steps that should always happen.",
      "Document one core process this month: the one most likely to break if you're unavailable.",
    ],
    relatedServiceIds: ["ai-workflow-automation", "crm-setup"],
    questions: [
      {
        id: "systems-documented",
        categoryId: "systems-operations",
        prompt: "Are your core processes documented anywhere (not just in your head)?",
        signal: "positive",
        weight: 1,
        quickCheck: true,
        maxPoints: 4,
        options: [
          { value: "documented", label: "Yes, documented", points: 4 },
          { value: "partially", label: "Partially", points: 2 },
          { value: "in-my-head", label: "All in my head", points: 0 },
        ],
      },
      {
        id: "systems-owner-dependency",
        categoryId: "systems-operations",
        prompt: "If you were out for two weeks, would the business run smoothly?",
        signal: "risk",
        weight: 1,
        quickCheck: false,
        maxPoints: 4,
        options: [
          { value: "yes-smoothly", label: "Yes", points: 4 },
          { value: "mostly", label: "Mostly", points: 2 },
          { value: "would-struggle", label: "It would struggle", points: 0 },
        ],
      },
    ],
  },
  {
    id: "ai-automation-readiness",
    label: "AI & Automation Readiness",
    description: "Whether repetitive work is automated, and openness to doing more of that.",
    weight: 6,
    enabled: true,
    relevantIndustries: "all",
    displayOrder: 9,
    effortProxy: 3,
    thresholds: { strong: 70, weak: 40 },
    positiveIndicatorHints: ["Some repetitive tasks already automated", "Openness to using AI tools"],
    riskIndicatorHints: ["No automation in place yet"],
    recommendedActionsByWeakness: [
      "Pick one repetitive task (follow-up, scheduling, FAQs) and automate that single workflow first.",
    ],
    relatedServiceIds: ["ai-chatbot", "ai-workflow-automation"],
    questions: [
      {
        id: "automation-in-place",
        categoryId: "ai-automation-readiness",
        prompt: "Are any repetitive tasks (scheduling, follow-up, FAQs) automated today?",
        signal: "positive",
        weight: 1,
        quickCheck: true,
        maxPoints: 4,
        options: [
          { value: "several", label: "Yes, several", points: 4 },
          { value: "one-or-two", label: "One or two", points: 2 },
          { value: "none-yet", label: "None yet", points: 0 },
        ],
      },
      {
        id: "automation-openness",
        categoryId: "ai-automation-readiness",
        prompt: "How open are you to using AI tools to save time?",
        signal: "risk",
        weight: 1,
        quickCheck: false,
        maxPoints: 4,
        options: [
          { value: "eager", label: "Yes, eager", points: 4 },
          { value: "cautious", label: "Open but cautious", points: 3 },
          { value: "not-interested", label: "Not interested", points: 1 },
        ],
      },
    ],
  },
  {
    id: "financial-discipline",
    label: "Financial Discipline",
    description: "Whether the numbers are tracked and there's a cushion for slow periods.",
    weight: 8,
    enabled: true,
    relevantIndustries: "all",
    displayOrder: 10,
    effortProxy: 2,
    thresholds: { strong: 70, weak: 40 },
    positiveIndicatorHints: ["Regular tracking of revenue and expenses", "A cash reserve for slow months"],
    riskIndicatorHints: ["No regular financial tracking", "No cash reserve"],
    recommendedActionsByWeakness: [
      "Set a recurring monthly check-in to review revenue and expenses, even 30 minutes counts.",
      "Start setting aside a small, consistent percentage of revenue as a reserve.",
    ],
    relatedServiceIds: [],
    questions: [
      {
        id: "financial-tracking",
        categoryId: "financial-discipline",
        prompt: "Do you track revenue and expenses on a regular schedule?",
        signal: "positive",
        weight: 1,
        quickCheck: true,
        maxPoints: 4,
        options: [
          { value: "monthly-plus", label: "Yes, monthly or more", points: 4 },
          { value: "occasionally", label: "Occasionally", points: 2 },
          { value: "rarely", label: "Rarely or never", points: 0 },
        ],
      },
      {
        id: "financial-reserve",
        categoryId: "financial-discipline",
        prompt: "Do you have a cash reserve for slow months?",
        signal: "risk",
        weight: 1,
        quickCheck: false,
        maxPoints: 4,
        options: [
          { value: "solid-reserve", label: "Yes, a solid reserve", points: 4 },
          { value: "small-buffer", label: "A small buffer", points: 2 },
          { value: "none", label: "None", points: 0 },
        ],
      },
    ],
  },
  {
    id: "leadership-team",
    label: "Leadership & Team",
    description: "How clearly roles and expectations are set, for businesses with a team.",
    weight: 5,
    enabled: true,
    relevantIndustries: "all",
    displayOrder: 11,
    effortProxy: 4,
    thresholds: { strong: 70, weak: 40 },
    positiveIndicatorHints: ["Clearly defined roles and expectations", "Regular check-ins with the team"],
    riskIndicatorHints: ["Unclear roles or expectations for the team"],
    recommendedActionsByWeakness: [
      "Write down expectations for each role clearly enough that anyone could follow them.",
      "Start a short, regular check-in rhythm with the team.",
    ],
    relatedServiceIds: ["monthly-growth-partnership"],
    questions: [
      {
        id: "leadership-roles-clear",
        categoryId: "leadership-team",
        prompt: "If you have a team, are roles and expectations clearly defined?",
        signal: "positive",
        weight: 1,
        quickCheck: false,
        maxPoints: 4,
        options: [
          { value: "clear", label: "Yes, clear", points: 4 },
          { value: "somewhat", label: "Somewhat", points: 2 },
          { value: "no", label: "No", points: 0 },
          { value: "solo", label: "It's just me right now", points: 3 },
        ],
      },
      {
        id: "leadership-checkins",
        categoryId: "leadership-team",
        prompt: "Do you have regular check-ins or performance conversations with your team?",
        signal: "risk",
        weight: 1,
        quickCheck: false,
        maxPoints: 4,
        options: [
          { value: "regular", label: "Yes, regular", points: 4 },
          { value: "occasionally", label: "Occasionally", points: 2 },
          { value: "no", label: "No", points: 0 },
          { value: "solo", label: "It's just me right now", points: 3 },
        ],
      },
    ],
  },
  {
    id: "founder-sustainability",
    label: "Founder Sustainability",
    description: "Whether the business supports the owner's life instead of consuming it.",
    weight: 5,
    enabled: true,
    relevantIndustries: "all",
    displayOrder: 12,
    effortProxy: 3,
    thresholds: { strong: 70, weak: 40 },
    positiveIndicatorHints: ["A sustainable current workload", "A business that supports life outside of work"],
    riskIndicatorHints: ["An unsustainable current pace", "The business consuming health, family, or personal time"],
    recommendedActionsByWeakness: [
      "Protect one fixed boundary this week (a day, an hour, a commitment) even if the business pushes against it.",
      "Identify the single task most responsible for the current workload and look for a way to reduce or delegate it.",
    ],
    relatedServiceIds: ["monthly-growth-partnership"],
    questions: [
      {
        id: "sustainability-workload",
        categoryId: "founder-sustainability",
        prompt: "How sustainable does your current workload feel?",
        signal: "positive",
        weight: 1,
        quickCheck: false,
        maxPoints: 4,
        options: [
          { value: "sustainable", label: "Sustainable", points: 4 },
          { value: "tight", label: "Manageable but tight", points: 2 },
          { value: "not-sustainable", label: "Not sustainable", points: 0 },
        ],
      },
      {
        id: "sustainability-life-balance",
        categoryId: "founder-sustainability",
        prompt: "Does the business currently support your life outside of work (family, health, etc.) reasonably well?",
        signal: "risk",
        weight: 1,
        quickCheck: false,
        maxPoints: 4,
        options: [
          { value: "yes", label: "Yes", points: 4 },
          { value: "somewhat", label: "Somewhat", points: 2 },
          { value: "not-really", label: "Not really", points: 0 },
        ],
      },
    ],
  },
];
